CREATE TYPE "public"."estado_busqueda" AS ENUM('CHECKED', 'UNCHECKED');--> statement-breakpoint
CREATE TYPE "public"."estado_expediente" AS ENUM('ACTIVE', 'ARCHIVED');--> statement-breakpoint
CREATE TYPE "public"."extracto" AS ENUM('ZM', 'FRNS', 'PENALT', 'POPF', 'LABORAL');--> statement-breakpoint
CREATE TABLE "expdynts_busqueda_check" (
	"id" serial PRIMARY KEY NOT NULL,
	"status" "estado_busqueda" DEFAULT 'CHECKED' NOT NULL,
	"descripcion" text,
	"ultima_ejecucion" timestamp,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "expdynts_expedientes" (
	"id" serial PRIMARY KEY NOT NULL,
	"exp" integer NOT NULL,
	"fecha" integer NOT NULL,
	"extracto" "extracto" NOT NULL,
	"cve_juz" varchar(255) NOT NULL,
	"acuerdos_nuevos" text DEFAULT '',
	"acuerdos_anteriores" text DEFAULT '',
	"hash_nuevo" varchar(255) DEFAULT '',
	"hash_anterior" varchar(255) DEFAULT '',
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "expdynts_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "expdynts_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "expdynts_usuario_attributes" (
	"usuario_id" integer PRIMARY KEY NOT NULL,
	"nombre_usuario" varchar(255),
	"apellido" varchar(255),
	"phone_number" varchar(15),
	"preferencias" json,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "expdynts_usuario_expedientes" (
	"id" serial PRIMARY KEY NOT NULL,
	"usuario_id" integer NOT NULL,
	"expediente_id" integer NOT NULL,
	"status" "estado_expediente" DEFAULT 'ACTIVE' NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "expdynts_usuarios" (
	"id" serial PRIMARY KEY NOT NULL,
	"external_id" varchar(255),
	"email" varchar(255) NOT NULL,
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "expdynts_usuarios_external_id_unique" UNIQUE("external_id"),
	CONSTRAINT "expdynts_usuarios_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "expdynts_usuario_attributes" ADD CONSTRAINT "expdynts_usuario_attributes_usuario_id_expdynts_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."expdynts_usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expdynts_usuario_expedientes" ADD CONSTRAINT "expdynts_usuario_expedientes_usuario_id_expdynts_usuarios_id_fk" FOREIGN KEY ("usuario_id") REFERENCES "public"."expdynts_usuarios"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expdynts_usuario_expedientes" ADD CONSTRAINT "expdynts_usuario_expedientes_expediente_id_expdynts_expedientes_id_fk" FOREIGN KEY ("expediente_id") REFERENCES "public"."expdynts_expedientes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "busqueda_check_ejecucion_idx" ON "expdynts_busqueda_check" USING btree ("ultima_ejecucion");--> statement-breakpoint
CREATE INDEX "expedientes_exp_idx" ON "expdynts_expedientes" USING btree ("exp");--> statement-breakpoint
CREATE INDEX "name_idx" ON "expdynts_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "usuario_attributes_phone_idx" ON "expdynts_usuario_attributes" USING btree ("phone_number");--> statement-breakpoint
CREATE UNIQUE INDEX "usuario_expediente_unq" ON "expdynts_usuario_expedientes" USING btree ("usuario_id","expediente_id");--> statement-breakpoint
CREATE INDEX "usuario_expedientes_status_idx" ON "expdynts_usuario_expedientes" USING btree ("status") WHERE status = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "usuarios_email_idx" ON "expdynts_usuarios" USING btree ("email");